### PR TITLE
fixed typos, add more explanations in Issue Resolution Duration for Filters

### PR DESCRIPTION
**Pull request by eyehwan**
fixed typos, change key word `proxy` to `dimension`, add more explanations in `Issue Resolution Duration` for **Filters**

### CODE REVIEW

**Comment by klumb** [comment]
I am not sure about changing proxy to dimension. They are not synonyms. 

Changing this term changes the narrative and meaning of the text (possibly in a good way).

Was there a discussion about this somewhere?

**Comment by eyehwan** [comment]
> Was there a discussion about this somewhere?

No, this is the place we start the discussion first. :)

> I am not sure about changing proxy to dimension. They are not synonyms.
Changing this term changes the narrative and meaning of the text (possibly in a good way).

"proxy" from my understanding is more like represented as “act on behalf of”, like [Java Dynamic Proxy Classes](https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/proxy.html) or [Proxy server](https://en.wikipedia.org/wiki/Proxy_server).
But here `Although code changes can be a **proxy** to the coding activity of a project`, makes me confused somewhat. 
If I changed it to **dimension**, it looks more clear that `code change is a dimension of measuring the the coding activity of a project`

I am not a native English speaker. I hope that I understand correctly on the these metrics, which is quite important and nice! 👍

**Comment by klumb** [comment]
No worries @eyehwan. It is a good discussion and edits are most certainly welcome. 

Both terms work here but they mean different things. 

Dimension may be the better word but I would like to get some other opinions on it because it does change the meaning of the text. I am not sure if it changes it in a substantial way, but if it does, we would need to send this metric back to review.

@sgoggins @foundjem -  what do you think?

**Review by sgoggins — CHANGES_REQUESTED** [review]
The Evolution working group thinks this line change to code-changes-lines, code-changes, change-requests-accepted, change-requests, and change-requests-declined should be reverted: 

```
  Although code changes can be a proxy to the coding activity of a project,
  Although code changes can be a dimension to the coding activity of a project,
```

**Comment by sgoggins** [comment]
> The Evolution working group thinks this line change to code-changes-lines, code-changes, change-requests-accepted, change-requests, and change-requests-declined should be reverted:
> 
> ```
>   Although code changes can be a proxy to the coding activity of a project,
>   Although code changes can be a dimension to the coding activity of a project,
> ```

During the July 7, 2021 Evolution working group meeting, we discussed these points at length. "Proxy" has a very specific meaning that clearly represents how people use many Evolution metrics as a "proxy for activity". This word will remain, and we welcome your other changes!! THANK YOU!!!

**Comment by eyehwan** [comment]
@sgoggins  Thanks for the declarations! Then I will push another patch for the rest of fixes.

**Comment by eyehwan** [comment]
I have updated another patch, to revert dimension back to proxy.

**Pull request merged**
