### PR TITLE
[docs] Improve Implementations README and add second requirements.txt

### PR DESCRIPTION
**Pull request by Polaris000**
This patch improves the README file with images and gifs and adds a second requirements.txt file specifically for notebooks.

### CODE REVIEW

**Comment by Polaris000** [comment]
Please have a look @valeriocos @jgbarah

**Comment by Polaris000** [comment]
@ccarterlandis: could you merge this?

**Comment by sgoggins** [comment]
@jgbarah : What are your thoughts on merging this one?

**Comment by sgoggins** [comment]
@Polaris000 : We are closing this now because the working group took Jupyter Notebook maintenance out of its sphere .

**Comment by Polaris000** [comment]
Thanks for the update @sgoggins.

**Pull request closed without merging**
