### PR TITLE
Create metrics-release-criteria

### PR DESCRIPTION
**Pull request by sgoggins**
Wanting some ready guidance available for people who want to develop metrics.

### CODE REVIEW

**Comment by jgbarah** [comment]
Re-reading the [CONTRIBUTING file](https://github.com/chaoss/wg-evolution/blob/master/CONTRIBUTING.md), maybe it already describes the process of how to propose metrics, and how to accept, with enough detail. If any, I would suggest to modify it, instead of creating a new file.

That do you think?

**Comment by germonprez** [comment]
I think there should be a single file for all WGs that describes this process. What is here is really about an external person wishing to bring something forward. I think that the process by which a metric is released will be slightly different. I'll put such a document in the Metrics repo.

**Comment by jgbarah** [comment]
@germonprez, sorry, I didn't understand. Do you mean that the `CONTRIBUTING.md` file in this repo should remain as such, and that we should have a description of the release process in the metrics repo? Or something else?

**Comment by sgoggins** [comment]
@GeorgLink : This is trying to solve the problem of people in working groups having to go to 2-5 different places in order to contribute. I think a little redundancy is helpful because we want people who are not on the calls to contribute. Even though I am on many calls, I still find it sometimes unclear how the different groups will decide metrics are ready to release. We actually left that to the working groups explicitly, I believe. I am fine with this document going away at some point, but right now I think we have too many places to look for important information.

**Comment by sgoggins** [comment]
@jgbarah : I think as long as we distinguish between the contributing process and the releasing process for metrics into "these are metrics we actually worked out" view, and how we make the transition from metrics approved in the repository to metrics that we release clear, it works for me ... I would like to make a push for developing metrics, and some basic standard for saying, these are "ready to release" and "these are not". 

Some aspect of the CHAOSS community has been reticent to "release" the metrics we approved thus far, so it "feels" like there is some standard or check beyond contributing that is expected. Perhaps not, and if not, then the contributing doc with a few more words might do the trick.

**Comment by germonprez** [comment]
Here is a draft for articulating the criteria for the release of metrics from a WG. 

As WGs prepare metrics for release they should meet the following criteria: 

1) The WG has a defined focus area with goal within which the metric resides
2) The metric answers a specific question associated with respect to the focus area 
3) The metric has a detailed metrics page associated with it. For example, a page that provides: 

1. Description
2. Use Cases
3. Formula
4. Sample Filter and Visualization
5. Sample Implementation
6. Known Implementations
7. Test Cases (Examples)
8. External References (Literature)

**Comment by jgbarah** [comment]
> Here is a draft for articulating the criteria for the release of metrics from a WG.
> ...

Thanks for the summary, @germonprez. Maybe I was too quick: I was not thinking on metrics that didn't have all of this. I was mostly thinking of metrics that had all of this, but maybe didn't have the consensus of the wg, which is something that up to now didn't happen, because of the discussion in issues, and the peer review process.

I'm ok with your proposal, and I agree with you that it should be in the metrics repository, likely linked from somewhere (I suggest the `CONTRIBUTING.md` file) in each working group repository.

WRT the template for the metric, if we want to specify one, i suggest that we follow the one in the "ready to release" metrics in this wg, just because we had the opportunity to flesh out and complete a bit previous templates.

**Comment by jgbarah** [comment]
> @jgbarah : I think as long as we distinguish between the contributing process and the releasing process for metrics into "these are metrics we actually worked out" view, and how we make the transition from metrics approved in the repository to metrics that we release clear, it works for me ... I would like to make a push for developing metrics, and some basic standard for saying, these are "ready to release" and "these are not".

OK, I see. Then, maybe what @germonprez suggests is good enough in this direction?

> Some aspect of the CHAOSS community has been reticent to "release" the metrics we approved thus far, so it "feels" like there is some standard or check beyond contributing that is expected. Perhaps not, and if not, then the contributing doc with a few more words might do the trick.

Yeah, I think i see the general feeling.

So, i suggest that we have two texts:

* One would be project-wide, along the lines @germonprez comments, likely in the `metrics` repo. It would mention the minimum criteria for a metric to be "releaseable" (if that is a word ;-) ).
* Another one would be specific for each working group, in the `CONTRIBUTING.md` or in  a spearate file (in this case, i suggest the name `RELEASING.md`, just because I guess that's a standard practice), defining the specific process the working group uses to decide that a metric is considered as released.

If you all agree with this, maybe we should widen the discussion about the first item to the whole CHAOSS community (I suggest preparing a pull request to the metrics repo, and then proposing the discussion, to focus the matter), and we just merge this pr (maybe renaming the file to `RELEASING.md`) as a first iteration of a wg defining "formally" the process for approval.

What do you think?

**Comment by germonprez** [comment]
Hi @jgbarah and thanks for this. I'll get together a releasing.md file for the metrics repo and issue the pull request today, spelling out the points above. You can then circulate to the wider community. Sounds like a plan.

**Comment by jgbarah** [comment]
I saw the releasing.md file during the CHAOSS weekly meeting today. Can we close this pull request, and if needed continue refining that file?

**Comment by jgbarah** [comment]
We agree in closing during our biweekly meeting.

**Pull request closed without merging**
