### PR TITLE
Standardized Repo Structure

### PR DESCRIPTION
**Pull request by yash2002109**
Hello everyone,
I have standardized the repo structure as discussed in #405 and #395. 

I have created a new `focus-areas` directory. The released metrics have been sorted into their focus areas in this directory. I have created an `images` subfolder in each of these focus areas to include the images required for the correct display of these metrics.
I have also included README.md files listing down the files and folders present at each level. The [metrics](https://github.com/chaoss/wg-evolution/tree/master/metrics) and [focus_areas](https://github.com/chaoss/wg-evolution/tree/master/focus_areas) folders have been left unmodified.

I have not yet renamed the files to match the template so that this PR doesn't become too messy. That can be done once these changes have been reviewed.

### CODE REVIEW

**Comment by klumb** [comment]
resolves #405

**Review by GeorgLink — CHANGES_REQUESTED** [review]
Thanks @yash2002109 

Please:
* Change the files names 
* Remove `./` from relative paths

**Comment by sgoggins** [comment]
@yash2002109 : Let me know when your branch is updated and this is ready for review, per @GeorgLink 's review.

**Comment by yash2002109** [comment]
I have made the required changes as suggested. Please review @GeorgLink @sgoggins.

**Comment by yash2002109** [comment]
Also while editing the markdown files, I noticed that at many places we have provided links to other metric files also. These links redirect to the markdown files in [metrics](https://github.com/chaoss/wg-evolution/tree/master/metrics) folder. 

I was thinking to edit those links, so they now redirect to markdowns in the newly created `focus-areas` folder.

**Comment by GeorgLink** [comment]
> Also while editing the markdown files, I noticed that at many places we have provided links to other metric files also. These links redirect to the markdown files in metrics folder.
> 
> I was thinking to edit those links, so they now redirect to markdowns in the newly created focus-areas folder.

We would prefer that any metric linked from within another metric points to the [released version on the website](https://chaoss.community/metrics/).

**Comment by yash2002109** [comment]
I have changed the links so they now redirect to the pages on the website. @GeorgLink, can you please take a look?

**Review by GeorgLink — APPROVED** [review]

**Review by GeorgLink — APPROVED** [review]
This looks great! Thanks @yash2002109 

@sgoggins, please review (do not merge).

After @sgoggins approves, @klumb needs to be the one to merge because he will also update the website.

**Pull request merged**
