### PR TITLE
[GSoC] Add documentation

### PR DESCRIPTION
**Pull request by Polaris000**
This pull request updates implementations README with
the latest metric implementations, structure of 
implementations as well instructions for adding
reference implementations.

### CODE REVIEW

**Comment by Polaris000** [comment]
Please have a look @jgbarah.

**Comment by Polaris000** [comment]
Do you suggest adding anything else on the main README page (for the whole repo) [here](https://github.com/chaoss/wg-evolution/pull/241/files#diff-04c6e90faac2675aa89e2176d2eec7d8)?

**Comment by jgbarah** [comment]
> Do you suggest adding anything else on the main README page (for the whole repo) [here](https://github.com/chaoss/wg-evolution/pull/241/files#diff-04c6e90faac2675aa89e2176d2eec7d8)?

I think we can start with this, and them improve it. But now, it is urgent that you produce your final blog post, and that you can link to this pr and the README files that explain the results of your work. So, I'm merging this for now. Feel free to pr with improvements to READMEs in the future, if you want.

**Comment by Polaris000** [comment]
Thanks for the review @jgbarah. I'll upload my final post soon, so that you and the other mentors can have a look and suggest changes.

**Pull request merged**
