### PR TITLE
[use_cases] New use case: Hints for maintainership position

### PR DESCRIPTION
**Pull request by jgbarah**
This is the first iteration of this use case. It does not include metrics yet, until we agree on the questions (as it is now, only a single question).

Any comment is appreciated, but comments by @kfogel are specially appreciated, since he started #48, which is the issue where we are discussing this use case.

### CODE REVIEW

**Comment by jgbarah** [comment]
@kfogel any feedback?

**Comment by jgbarah** [comment]
Since we're having no feedback, I'm proposing to merge this anyway, and if needed, work later on the resulting files. Do you agree?

**Comment by foundjem** [comment]
I agree.

**Comment by GeorgLink** [comment]
Merged as a first version of the use case. continue discussion in $48

**Pull request merged**
