### PR TITLE
[Licensing] Add licensing and rearrange a few imports

### PR DESCRIPTION
**Pull request by Polaris000**
This patch adds a few missing lines of 
documentation, adds licensing to all scripts and 
rearranges a few imports.

@jgbarah, @valeriocos,  please add your details as a contributor wherever you see fit. :)

### CODE REVIEW

**Comment by jgb** [comment]
> Thank you @Polaris000 , the PR looks good! @jgb feel free to have a look, thanks!

Again, I am not @jgbarah ...

**Comment by valeriocos** [comment]
sorry @jgb for the noise

**Comment by valeriocos** [comment]
@jgbarah we can merge it and reiterate on the code if needed

**Comment by jgbarah** [comment]
Yes, I agree, thanks a lot for merging.

**Pull request merged**
