### PR TITLE
add code_changes_lines grimoirelab example

### PR DESCRIPTION
**Pull request by GeorgLink**
This pull request implements the idea from #159 and adds to the metric "Code Changes Lines" details about how to get the metric in GrimoireLab.

This pull request is an idea for how we can make the metric definitions more actionable for users who are interested in using the metric.

Please provide comments and feedback.

This pr was created with the help of @alpgarcia, @mghfdez, and @dicortazar.

/cc @sduenas @valeriocos @sgoggins @jgbarah @germonprez

### CODE REVIEW

**Comment by GeorgLink** [comment]
Thanks @jgbarah: I fixed the DCO sign-off.

What do other WG members think about this approach of more closely linking metrics with software.

**Comment by jgbarah** [comment]
> What do other WG members think about this approach of more closely linking metrics with software.

I'm requesting review by some other people, and would merge this if no negative feedback is received.

**Comment by germonprez** [comment]
This came up in the June 11 CHAOSS community call. I hope that all metrics can have something like this. So I approve.

**Comment by jgbarah** [comment]
Great! Merging then. Thanks to everyone!

**Pull request merged**
